name: Update Octopus Tracker information

on:
  schedule:
    - cron: '0 11 * * *' # At 11:00 every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4  # Checkout repository so worflow can access it

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # Update Octopus Tracker information
        run: python octopus_tracker_svt_comparison.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update rates" --allow-empty)
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
